[package]
name = "film_grain_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
image = "0.24.6"
lerp = "0.4.0"
rand = "0.8.5"
